StartupEvents.registry('block', event => {

  event.create('test_crop', 'crop')
    .displayName('Test Crop')
    .crop('minecraft:wheat')
  event.create('overgrown_grout')
    .soundType('gravel')
    .hardness(0.5)
    .resistance(0.5)
    .tagBlock('minecraft:minable/shovel')

  event.create('crimtane_crop', 'crop')
  event.create('azure_crop', 'crop')
  event.create('spring_crop', 'crop')
  event.create('ashen_crop', 'crop')
  event.create('orchid_crop', 'crop')

  event.create('endless_frost_block')
    .soundType('glass')
    .hardness(1.0)
    .resistance(0.75)
    .requiresTool(true)
    .tagBlock('minecraft:minable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')

  event.create('end_portal_frame_base', 'cardinal')
    .soundType('stone')
    .hardness(1.0)
    .resistance(0.75)
    .requiresTool(true)
    .tagBlock('minecraft:minable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')
    .box(0, 0, 0, 16, 13, 16)
})