StartupEvents.registry('fluid', event => {
    event.create('molten_shadowsteel')
        .thickTexture(0x330F5D)
        .displayName('Molten Shadowsteel')
        .temperature(1200)
        .luminosity(5)
        .viscosity(1000)
        .noBlock()
        .bucketItem.texture('aeteris:item/molten_shadowsteel_bucket')
    event.create('fire_dragon_blood')
        .thickTexture(0xDA4E00)
        .displayName('Fire Dragon Blood')
        .temperature(1800)
        .luminosity(10)
        .viscosity(1000)
        .noBlock()
        .bucketItem.texture('aeteris:item/fire_dragon_blood_bucket')
})