StartupEvents.registry('fluid', event => {
    event.create('molten_shadowsteel')
        .thickTexture(0x330F5D)
        .displayName('Molten Shadowsteel')
        .temperature(1200)
        .luminosity(5)
        .viscosity(1000)
        .noBlock()
        .bucketItem.texture('aeteris:item/molten_shadowsteel_bucket')
    event.create('molten_mithril')
        .thickTexture(0x2effe5)
        .displayName('Molten Mithril')
        .temperature(1300)
        .luminosity(5)
        .viscosity(1000)
        .noBlock()
        .bucketItem.texture('aeteris:item/molten_mithril_bucket')
    
    event.create('fire_dragon_blood')
        .thinTexture(0xDA4E00)
        .displayName('Fire Dragon Blood')
        .luminosity(10)
        .viscosity(1000)
        .noBlock()
        .bucketItem.texture('aeteris:item/fire_dragon_blood_bucket')
    event.create('ice_dragon_blood')
        .thinTexture(0x2AE2FF)
        .displayName('Ice Dragon Blood')
        .luminosity(10)
        .viscosity(1000)
        .noBlock()
        .bucketItem.texture('aeteris:item/ice_dragon_blood_bucket')
    event.create('lightning_dragon_blood')
        .thinTexture(0xB317FF)
        .displayName('Lightning Dragon Blood')
        .luminosity(10)
        .viscosity(1000)
        .noBlock()
        .bucketItem.texture('aeteris:item/lightning_dragon_blood_bucket')

    event.create('superheating_fuel')
        .thickTexture(0x009fff)
        .displayName('Superheating Fuel')
        .temperature(1500)
        .luminosity(15)
        .viscosity(1200)
        .noBlock()
        .bucketItem.texture('aeteris:item/superheating_fuel_bucket')
    
    event.create('glow_ink')
        .thinTexture('aeteris:block/glow_ink_still')
        .stillTexture('aeteris:block/glow_ink_still')
        .flowingTexture('aeteris:block/glow_ink_flowing')
        .displayName('Glow Ink')
        .temperature(20)
        .luminosity(7)
        .viscosity(1000)
        .noBlock()
})