version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
leavesCullingMode = "DEPTH"
leavesCullingAmount = 2
includeMangroveRoots = true
powderSnowCulling = true
endGatewayCulling = false
beaconBeamCulling = true
entityModelCulling = false
useOnModdedBlocksByDefault = true

[modCompatibility]
kubejs = true
createfood = true
tconstruct = true
farmersdelight = true
cratedelight = true
create_vibrant_vaults = true
botania = true
magnumtorch = true
chipped = true
storagedrawers = true
culturaldelights = true
create = true
create_ironworks = true
ironchest = true
star = true
refurbished_furniture = true
twigs = true
copycats = false
lootr = true
minecraft = true
fabricaeexnihilo = true
rusticdelight = true
usefulbackpacks = true
comforts = true
iceandfire = true
ends_delight = true
nethersdelight = true
createdeco = true
create_jetpack = true
create_enchantment_industry = true
createaddition = true
create_dd = true
railways = true
milk = true
botanypots = true
amendments = true
waystones = true
advancement-book-updated = true
hephaestusplus = true
tacz = true
computercraft = true
createsifter = true
toms_peripherals = true
basic_fluid_hopper = true
woodenhoppers = true
expandeddelight = true
delightfulcreators = true
gravestones = true
